# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '* * 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run start --if-present
    - name: Commit git
      run: |
        git config --local user.email 'lxuan2497@gmail.com'
        git config --local user.name 'lxuan'
        git pull
        git add README.md
        git commit -m 'update README.md'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
